### ISSUE TITLE
Redefine the `rqa` function

### ISSUE THREAD

**Issue by heliosdrm** [JuliaDynamics/RecurrenceAnalysis.jl#105]
The `rqa` function has two issues right now:

* With the addition of `TRANS`, when the input is a nonsquare matrix it return `TRANS=false` with a warning. Maybe it would make more sense to skip that parameter.
* It is type-unstable: it returns a `NamedTuple` with a different set of elements depending on the keyword argument `onlydiagonal`.

(Breaking) proposal: change it to two different functions depending on whether diagonal-related parameters are wanted or not. `TRANS` could be skipped for `CrossRecurrenceMatrix` inputs, which are not guaranteed to be square.

**Comment by Datseris** [comment]
sure

**Comment by heliosdrm** [comment]
An alternative to keep a single function, but type-stable, would be reverting 4e38bed (previous to 1.0) and make `rqa` return a `Dict`, instead of a `NamedTuple`. That change was meant to gain speed (the comment said "This should be faster than using a Dict"); but I think that we did not considered the drawbacks, and maybe the flexibility of `Dict`s compensates the potential (although I don't know if measured) gain of speed.

**Comment by Datseris** [comment]
damn, I shouldn't have accepted that PR. We're talking about nanosecond performance differences that guide design decisions. Return type of `rqa` is much better as a dict. But this is breaking and should move the library to 2.0 if it happens.

**Comment by heliosdrm** [comment]
Thinking twice on this, a less breaking alternative would be to return always a named tuple with all the possible fields, but filled with `NaN` in those fields that are not calculated.

Or maybe even a new `RQA` type instead of a tuple, such that it would be possible to control what fields are available or not, depending on how it was created.

In either case, I could still do `result = rqa(R)` and then `result.DET` to see the determinism, etc., so the change would not be as disruptive as going back to dictionaries.

**Comment by Datseris** [comment]
Hm, while it is indeed convenient to access things with `.DET`, I still believe that the dictionary is more fitting here. The quantities contained in the return of the `RQA` are a lot, and constantly increasing. This is not what Named Tuples are meant for. Tuples and Named Tuples are meant for small amount of things that do **never change size**. This perhaps is the best reason to not use a named tuple. Everytime a user wants to contribute a new RQA quantity, the type of the return argument would break.

This is why I'm favor of a dictionary, which is more suitable given the Julia language.

For the custom struct, sure that is fine with me, but only if its a wrapper of a standard Julia dictionary. Having a struct that has "different fields" depending on some options feels unintuitive and untypical for Julia propramming. If its a wrapper of a Dict, you can define indexing both for `["DET"]` and `.DET`. Howewer, I don't think this is worth doing, because why try to extend the several dozen methods a dictionary has, instead of just using a Dictionary directly...?

**Comment by Datseris** [comment]
Yes that sounds like a good idea. Me the `getproperty` method issue a warning but the `getindex` method to not do that.

**Comment by heliosdrm** [comment]
What do you think about using strings or symbols as keys of the dictionary? There is an advantage of symbols in the current situation (well, not a big advantage, but maybe...): named tuples can be indexed like dictionaries with symbol keys, such that the result of `rqa` as it is can be indexed both `x.DET` or `x[:DET]`, etc. I don't mean that many people will be doing it that way, but in the cases where it is done, no change in their code would be needed.

**Comment by Datseris** [comment]
For our implementation, using strings or symbols for the key type makes no functional difference so sure, I would go with symbols. You'd have to be careful though to never create a name with whitespace in it in the future (because it becomes really clunky to make a symbol with white space)
