### ISSUE TITLE
unexpected behaviour for arrays as input

### ISSUE THREAD

**Issue by pucicu** [JuliaDynamics/RecurrenceAnalysis.jl#106]
I have imported data using `readdlm`, e.g., into variable _x_. The result is a `1001×5 Array{Float64,2}`. When I use, e.g., `x1 = x[:,5]` (resulting in `1001-element Array{Float64,1}`), then I can calculate `R = RecurrenceMatrix(x1, ε; fixedrate = true)`. But it does not work when I use the entire array _x_ , i.e., `R = RecurrenceMatrix(x, ε; fixedrate = true)`. I get this error:
`ERROR: MethodError: no method matching recurrence_matrix(::Array{Float64,2}, ::Euclidean, ::Float64, ::Val{true})`

This is completely unexpected.

**Comment by Datseris** [comment]
Multidimensional data in the DynamicalSystems.jl ecosystem are expected in the form of `Dataset` and not `Matrix`. This is explained here: https://juliadynamics.github.io/DynamicalSystems.jl/dev/#Getting-started-1  as well as here https://juliadynamics.github.io/DynamicalSystems.jl/dev/embedding/dataset/ .

So, you have to give `Dataset(your_matrix)` to the function.

Hm, but I now checked the docstring of `RecurrenceMatrix` and it says that it can accept a `Matrix`. That's unfortunate, it is a remnant of a previous version. I (personally) don't agree with adding an automatic conversion from matrix to dataset in `RecurrenceMatrix`, because such conversions must be done manually in every single function of the ecosystem. I find more reasonable to use the expected form instead.

**Comment by pucicu** [comment]
ok, I see. this increases of course the complexity of the user interface, but I understand that you have good reason for this.

therefore, I suggest to add a corresponding hint when this error is catched. instead of the auto-conversion from array to dataset.

**Comment by Datseris** [comment]
> but I understand that you have good reason for this.

yes, the dimensionality of datapoints of `Matrix` is not known by type, which leads to inferior performance down the line.

**Comment by heliosdrm** [comment]
Closed by #107: matrix inputs work now with all functions, but issue a deprecation warning; in the future it should be the other way round - throw an error with an informative message informing of the correct call.
