### ISSUE TITLE
Bump UnicodePlots version

### ISSUE THREAD

**Issue by allomulder** [JuliaDynamics/RecurrenceAnalysis.jl#138]
Hello,

[UnicodePlots](https://github.com/JuliaPlots/UnicodePlots.jl) has been updated to 3.0.0 and up for quite a while. Judging by [description](https://github.com/JuliaPlots/UnicodePlots.jl/pull/272), it offers quite a performance improvement. Maybe consider bumping compat version?

**Comment by Datseris** [comment]
Sure, wanna do a PR that increases this version?

**Comment by allomulder** [comment]
@Datseris I'm a bit of a Julia newbie and just trying out things for now, so it might take a while for me :D But yes, I'd like to try, if noone beats me to it.

**Comment by Datseris** [comment]
Don't worry. It isn't very difficult. First, do `dev RecurrenceAnalysis`. It will make a local copy of the repo for you. Go into it, in Project.toml, and increase the version that bounds UnicodePlots. Then, restart Julia, update (so that the new version of Unicode Plots is downloaded), and just `using RecurrenceAnalysis` and make a trivial RR matrix. If it shows correctly in e.g., VSCode, we're good to go, and you can push your local code to your fork on GitHub and open a PR here!

**Comment by allomulder** [comment]
@Datseris seems like I did that and the world hasn't collapsed immediately. Guess that's a good result :D 

Thank you for you help and check out PR #139, please
