### ISSUE TITLE
Functions for analysis of (cross-)recurrence networks

### ISSUE THREAD

**Issue by heliosdrm** [JuliaDynamics/RecurrenceAnalysis.jl#23]
This includes the calculation of:

- [ ] Adjacency matrix (based on `recurrencematrix`)
- [ ] Edge density (based on `recurrencerate`)
- [ ] Global clustering coefficient or network transitivity
- [ ] Average path length
- [ ] Global efficiency

**Comment by pucicu** [comment]
Hi,

would be good to have also the Laplace matrix and the Eigenvalue spectrum.
See:

D. Eroglu, N. Marwan, S. Prasad, J. Kurths: Finding recurrence networks' threshold adaptively for a specific time series, Nonlinear Processes in Geophysics, 21, 1085–1092 (2014). DOI:10.5194/npg-21-1085-2014 <http://dx.doi.org/10.5194/npg-21-1085-2014>

Best wishes for the new year!
Norbert

**Comment by heliosdrm** [comment]
Going back to old issues, and I found this one, half-forgotten. Now we already have the `transitivity` function and the TRANS parameter from the `rqa` function, although without having the type `AdjacencyMatrix <: AbstractRecurrenceMatrix` that was suggested originally in this issue.

In #105 and #108 we were discussing the problem of TRANS not being applicable to non-square matrices. If we recover the idea of creating a specific type for `AdjacencyMatrix`, perhaps we could make `rqa` return a different set of parameters for that type of matrices, including transitivity and the rest of parameters mentioned above (edge density, average path length, global efficiency).

**Comment by Datseris** [comment]
Yes, I agree with this suggestion. Define the type, however I would call it `AdjacencyRecurrenceMatrix`, as adjacency by itself might mislead in the direction of e.g. LightGraphs.jl. 

Now that I mention this, have you checked LightGraphs? They might already have functions for all the quantities you mention.

**Comment by heliosdrm** [comment]
Oh dear! Yes, LightGraphs seems pretty exhaustive. They have, for instance, the concept of transitivity implemented as [`global_clustering_coefficient`](https://juliagraphs.org/LightGraphs.jl/stable/community/#LightGraphs.global_clustering_coefficient-Tuple{AbstractGraph}), and also edge [`density`](https://juliagraphs.org/LightGraphs.jl/stable/core/#LightGraphs.density). Maybe the others too, and if not, I think it would make more sense to contribute to that package rather than implementing them here. After all, recurrence network analysis consists in borrowing the methods from graph theory to analyze time series, using the equivalence between recurrence matrices and adjacency matrices as a bridge.

Perhaps we could make here a function that takes a recurrence matrix, and makes a string in GML or GraphML format that describes its corresponding graph, such that one can use that result as an input for LightGraphs and then do the network analysis with that package, instead of this one.

**Comment by Datseris** [comment]
Why not directly transform the recurrence matrix to a `LightGraphs.SimpleGraph`?

**Comment by heliosdrm** [comment]
To avoid including LightGraphs as dependency and import it?

**Comment by Datseris** [comment]
One way to go about it is to do the original proposal of writing output into a string, then loading with LightGraphs.jl, then trying to find all analysis functions that are used on the Recurrence Network Analysis approach. This has the benefit of being more lightweight on RecurrenceAnalysis.jl on the expense of user experience.

The other way is to simply include LightGraphs.jl here, provided a direct transformation, and define a new `rna` function, which similarly to `rqa` provides a collection of the measures mentioned in this post.

I think the 2nd way is the direction we should head. First of all, LightGraphs.jl is one of the premier and most well known Julia packages. Secondly, it is a surprisingly lightweight dependency https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/Project.toml  (I guess the name isn't just for show ;) ). Thirdly, many of the issues raised in  @pucicu  post [here](https://github.com/JuliaDynamics/RecurrenceAnalysis.jl/pull/102#issuecomment-736108329) are addressed by such approaches that are more unifying, and make overall usage and user experience smoother. (by the way I will address this comment, it is on my to-do list I haven't forgotten about it).

That's why my vote is the second approach. After all, for users installing RQA as part of the DynamicalSystems.jl installation, LightGraphs.jl is literally nothing when compared to installing packages of differential equations.

**Comment by heliosdrm** [comment]
After exploring LightGraphs, I have found the following recurrence network parameters already available (function names in parentheses):

* local degree centrality, i.e. number of connected vertices for each hone (`degree`)
* edge density, i.e. average degree density (`density`)
* local clustering coefficient (`local_clustering_coefficient`)
* closeness centrality (`closeness_centrality`)
* betweenness centrality (`betweenness_centrality`)
* transitivity (`global_clustering_coefficient`)

There are also the functions [`laplacian_matrix`](https://juliagraphs.org/LightGraphs.jl/stable/linalg/#LightGraphs.LinAlg.laplacian_matrix-Union{Tuple{AbstractGraph{U}},%20Tuple{U},%20Tuple{AbstractGraph{U},DataType}}%20where%20U) and [`laplacian_spectrum`](https://juliagraphs.org/LightGraphs.jl/stable/linalg/#LightGraphs.LinAlg.laplacian_spectrum) that might give the results that Norbert had suggested:

> would be good to have also the Laplace matrix and the Eigenvalue spectrum. See: D. Eroglu, N. Marwan, S. Prasad, J. Kurths: Finding recurrence networks' threshold adaptively for a specific time series, Nonlinear Processes in Geophysics, 21, 1085–1092 (2014). DOI:10.5194/npg-21-1085-2014 <http://dx.doi.org/10.5194/npg-21-1085-2014>

I only find missing the harmonic centrality, which might be used to calculate the parameter of global efficiency. If you think that it is relevant, I could make a PR for LightGraphs.

**Comment by pucicu** [comment]
Hi
thanks!
At the moment, I have no idea how harmonic centrality and recurrence would be related. We could look at it later.

Best
N

**Comment by heliosdrm** [comment]
Closed by #112
