### ISSUE TITLE
Ambiguous definition of `Dataset`

### ISSUE THREAD

**Issue by heliosdrm** [JuliaDynamics/RecurrenceAnalysis.jl#69]
When I run some examples of recent issues, where I create `Dataset`s from `DynamicalSystemsBase` (e.g. a Lorenz system) and then try to analyze them with `RecurrenceMatrix` etc., I get an error because the type of `Dataset` that the functions of this package recognize is `RecurrenceAnalysis.Dataset`, but they are `DynamicalSystemsBase.Dataset`.

I don't know if this is something that is wrong in my configuration...

**Comment by Datseris** [comment]
Yeah this is something wrong in your configuration, in my side it works fine. I have had the suspicion that something is wrong in your config because I saw that in the tests you explicitly use `RecurrenceAnalysis.Dataset`. I believe this has to do withe the Project.toml that was existing in previous versions of the repo.

Can you try a re-installation of all DynSys packages and see how it goes? You can start from DelayEmbeddings .

**Comment by heliosdrm** [comment]
Ok, my problem was that I had `DynamicalSystemsBase` installed in the "production" environment (with `add`), and `RecurrenceAnalysis` as "development" (with `dev`). It seems that Julia has some problem when trying to use a type defined in different environments in the same session. Solved with:

```
pkg> rm DynamicalSystemsBase
pkg> dev DynamicalSystemsBase
```
